[build]
  publish = "Auto_Gestao_de_Direcao_v0.1"

[[redirects]]
  from = "/Auto_Gestao_de_Direcao_v0.1"
  to = "/"
  status = 301

[[redirects]]
  from = "/Auto_Gestao_de_Direcao_v0.1/*"
  to = "/:splat"
  status = 301
