[build]
  publish = "Auto_Gestao_de_Direcao_v0.1"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/Auto_Gestao_de_Direcao_v0.1"
  to = "/"
  status = 301

[[redirects]]
  from = "/Auto_Gestao_de_Direcao_v0.1/*"
  to = "/:splat"
  status = 301
